globals:
  sites:
    - domain: localhost
      index: peerdb
      schema: peerdb
      features:
        searchResultsTable: true
        downloadButtons: true
      roles:
        admin:
          - canEditDocument
          - canChangesDocument
          - canGetFile
          - canChangesFile
          - canEditFile
