globals:
  sites:
    - domain: localhost
      indexPrefix: peerdb
      schema: peerdb
      languagePriority:
        en: []
        sl: []
      defaultLanguage: en
      features:
        searchResultsTable: true
        downloadButtons: true
        indexAncestorProperties: true
      roles:
        admin:
          - canEditDocument
          - canDeleteDocument
          - canChangesDocument
          - canBulkGetFile
          - canChangesFile
          - canEditFile
          - canDeleteFile
