globals:
  sites:
    - domain: localhost
      indexPrefix: peerdb
      schema: peerdb
      languagePriority:
        en: [und]
        sl: [en, und]
        pt: [en, und]
      defaultLanguage: en
      features:
        searchResultsTable: true
        downloadButtons: true
        indexAncestorProperties: true
      roles:
        "":
          ACTION_READ:
            - all
        historic:
          ACTION_READ_HISTORIC:
            - all
        bulk:
          ACTION_READ_BULK:
            - all
        create:
          ACTION_CREATE:
            - all
        update:
          ACTION_UPDATE:
            - all
        permissions:
          ACTION_UPDATE_PERMISSIONS:
            - all
        delete:
          ACTION_DELETE:
            - all
        admin:
          ACTION_READ_HISTORIC:
            - all
          ACTION_READ_BULK:
            - all
          ACTION_CREATE:
            - all
          ACTION_UPDATE:
            - all
          ACTION_UPDATE_PERMISSIONS:
            - all
          ACTION_DELETE:
            - all
