package auth

import (
	"context"
	"time"

	"github.com/coreos/go-oidc/v3/oidc"
	"gitlab.com/tozd/go/errors"
	"golang.org/x/oauth2"
)

// signInScopes are the scopes the backend requests during the OIDC
// authorization flow. "role.*" is Charon's wildcard that expands into the
// individual "role.<key>" grants the access token actually carries; without
// it Verifier.Authenticate sees an empty role set.
var signInScopes = []string{ //nolint:gochecknoglobals
	oidc.ScopeOpenID,
	"profile",
	"email",
	"role.*",
}

// oauthConfig returns a copy of the stored oauth2.Config with the redirect
// URL resolved via the thunk. We copy rather than mutate because the
// underlying config is shared across goroutines.
func (v *Verifier) oauthConfig() oauth2.Config {
	c := *v.oauth
	c.RedirectURL = v.redirectURI()
	return c
}

// AuthCodeURL builds the issuer-bound URL the browser should be redirected
// to in order to start an authorization-code flow. state, codeVerifier, and
// nonce must be generated by the caller. The PKCE verifier should come from
// oauth2.GenerateVerifier so the S256 challenge derivation matches what the
// issuer expects.
func (v *Verifier) AuthCodeURL(state, codeVerifier, nonce string) string {
	cfg := v.oauthConfig()
	return cfg.AuthCodeURL(
		state,
		oauth2.AccessTypeOnline,
		oauth2.S256ChallengeOption(codeVerifier),
		oidc.Nonce(nonce),
	)
}

// ExchangeCode finishes the authorization-code flow. It swaps the
// short-lived authorization code for a token set, validates the returned
// ID token against the verifier (signature, issuer, audience, expiry),
// optionally checks at_hash, primes the userinfo cache from the ID-token
// claims, and returns the access token and its expiration.
//
// The expectedNonce must match the nonce stored in the FlowStore for this
// flow. ID tokens with a missing or mismatched nonce are rejected.
func (v *Verifier) ExchangeCode(ctx context.Context, code, codeVerifier, expectedNonce string) (string, time.Time, errors.E) {
	// The pooled HTTP client is shared with JWKS / userinfo so token
	// exchanges benefit from the same keep-alive pool.
	tokenCtx := oidc.ClientContext(ctx, v.httpClient)
	cfg := v.oauthConfig()
	response, err := cfg.Exchange(tokenCtx, code, oauth2.VerifierOption(codeVerifier))
	if err != nil {
		return "", time.Time{}, errors.WithStack(err)
	}

	rawIDToken, ok := response.Extra("id_token").(string)
	if !ok || rawIDToken == "" {
		return "", time.Time{}, errors.New("issuer did not return an id_token")
	}

	idToken, err := v.verifier.Verify(ctx, rawIDToken)
	if err != nil {
		return "", time.Time{}, errors.WithStack(err)
	}
	if idToken.Nonce != expectedNonce {
		return "", time.Time{}, errors.New("id_token nonce mismatch")
	}
	// If the issuer included an at_hash claim, verify it matches the
	// access token. The claim is optional in the authorization-code flow,
	// so we only verify when present.
	if idToken.AccessTokenHash != "" {
		err = idToken.VerifyAccessToken(response.AccessToken)
		if err != nil {
			return "", time.Time{}, errors.WithStack(err)
		}
	}

	// Prime the userinfo cache from the ID-token claims so the first
	// authenticated request after sign-in does not pay an extra
	// /auth/oidc/userinfo round-trip.
	var profile struct {
		PreferredUsername string `json:"preferred_username"` //nolint:tagliatelle
	}
	err = idToken.Claims(&profile)
	if err != nil {
		return "", time.Time{}, errors.WithStack(err)
	}
	v.userInfoCache.set(idToken.Subject, userInfo{
		Subject:  idToken.Subject,
		Username: profile.PreferredUsername,
	})

	return response.AccessToken, response.Expiry, nil
}
