/**
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by generate-vue-i18n.js script based on src/locales/en.json.
 * To update this file, modify src/locales/en.json and run: npm run generate-vue-i18n.
 */

// This empty export makes TypeScript treat this file as a module.
export {}

declare module "vue-i18n" {
  export interface DefineLocaleMessage {
    common: {
      buttons: {
        search: string
        create: string
        upload: string
        edit: string
        save: string
        add: string
        remove: string
        loadCountMore: string
        loadMore: string
        filters: string
        prev: string
        next: string
      }
      status: {
        loading: string
        loadingDataFailed: string
        valuesNotShown: string
        allResults: string
        allResultsOnly: string
        allResultsMoreThan: string
      }
      labels: {
        property: string
        value: string
        timestamp: string
        precision: string
      }
      icons: {
        link: string
        feed: string
        table: string
      }
      values: {
        noName: string
        none: string
        unknown: string
      }
    }
    components: {
      InputTime: {
        format: string
        precision: {
          G: string
          "100M": string
          "10M": string
          M: string
          "100k": string
          "10k": string
          k: string
          "100y": string
          "10y": string
          y: string
          m: string
          d: string
          h: string
          min: string
          s: string
        }
        errors: {
          invalid: string
          daysNotZero: string
          months: string
          months0: string
          days: string
          days0: string
          hours: string
          minutes: string
          seconds: string
        }
      }
    }
    partials: {
      Footer: {
        poweredBy: string
      }
      SearchResultsHeader: {
        searchingQueryFilters: string
        searchingNoQueryFilters: string
        searchingQueryFiltersInProgress: string
        searchingNoQueryFiltersInProgress: string
        resultsFound: string
        resultsFoundMoreThan: string
        noResults: string
      }
      SearchResultsFeed: {
        moreFilters: string
        shownResults: string
        shownResultsOnly: string
        filtersNotShown: string
        noFilters: string
        filtersAvailable: string
        determiningFilters: string
      }
      SearchResultsTable: {
        expandRow: string
        collapseRow: string
        moreColumns: string
      }
      claimvalue: {
        ClaimValueFile: {
          filePreview: string
        }
      }
    }
    views: {
      DocumentGet: {
        tabs: {
          article: string
          file: string
          allProperties: string
        }
      }
      DocumentEdit: {
        addClaim: string
        claimTypes: {
          identifier: string
          reference: string
          text: string
          string: string
          amount: string
          amountRange: string
          relation: string
          file: string
          noValue: string
          unknownValue: string
          time: string
          timeRange: string
        }
        labels: {
          iri: string
          text: string
          string: string
          amount: string
          lower: string
          upper: string
          to: string
          mediaType: string
          url: string
          previewUrl: string
        }
      }
    }
  }
}
