/**
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is auto-generated by generate-vue-i18n.js script based on src/locales/en.json.
 * To update this file, modify src/locales/en.json and run: npm run generate-vue-i18n.
 */

// This empty export makes TypeScript treat this file as a module.
export {}

declare module "vue-i18n" {
  export interface DefineLocaleMessage {
    common: {
      buttons: {
        search: string
        cancel: string
        close: string
        create: string
        upload: string
        edit: string
        save: string
        discard: string
        add: string
        insert: string
        update: string
        clear: string
        remove: string
        revert: string
        subClaim: string
        loadCountMore: string
        loadMore: string
        filters: string
        prev: string
        next: string
        open: string
        unlink: string
        signIn: string
        signOut: string
      }
      errors: {
        unexpected: string
      }
      status: {
        editingNotAllowed: string
        loading: string
        loadingDataFailed: string
        error: string
        valuesNotShown: string
        allResults: string
        allResultsOnly: string
        allResultsMoreThan: string
      }
      labels: {
        property: string
        value: string
        time: string
        amount: string
        precision: string
        required: string
        multiple: string
        changed: string
      }
      icons: {
        link: string
        feed: string
        table: string
      }
      values: {
        missing: string
        noName: string
        none: string
        unknown: string
      }
      validation: {
        required: string
        requiredPrecision: string
        invalid: string
        invalidPrecision: string
      }
    }
    partials: {
      input: {
        InputHTML: {
          toolbar: {
            label: string
            undo: string
            redo: string
            blockType: string
            paragraph: string
            heading: string
            preformatted: string
            bold: string
            italic: string
            underline: string
            strikethrough: string
            monospace: string
            bulletList: string
            orderedList: string
            blockquote: string
            indent: string
            outdent: string
            horizontalRule: string
            lineBreak: string
            link: string
            attachFile: string
            replaceFile: string
          }
          bottomToolbar: {
            linkLabel: string
            blockquoteLabel: string
            fileLabel: string
            uploadingLabel: string
            dropFileLabel: string
          }
        }
        InputFile: {
          dropOrBrowse: string
        }
        InputRef: {
          invalidValue: string
          noResults: string
        }
        InputRefSelect: {
          noOptions: string
        }
        InputTime: {
          format: string
          precision: {
            G: string
            "100M": string
            "10M": string
            M: string
            "100k": string
            "10k": string
            k: string
            "100y": string
            "10y": string
            y: string
            m: string
            d: string
            h: string
            min: string
            s: string
            ms: string
            us: string
            ns: string
          }
          errors: {
            invalid: string
            daysNotZero: string
            months: string
            months0: string
            days: string
            days0: string
            hours: string
            minutes: string
            seconds: string
            subseconds: string
          }
        }
      }
      Footer: {
        poweredBy: string
      }
      SearchResultsHeader: {
        searchingQueryFilters: string
        searchingNoQueryFilters: string
        searchingQueryFiltersInProgress: string
        searchingNoQueryFiltersInProgress: string
        resultsFound: string
        resultsFoundMoreThan: string
        noResults: string
        downloadZip: string
        downloadFiles: string
      }
      DownloadOverlay: {
        preparing: string
        downloadingFile: string
        noFiles: string
        error: string
      }
      SearchResultsFeed: {
        moreFilters: string
        shownResults: string
        shownResultsOnly: string
        filtersNotShown: string
        noFilters: string
        filtersAvailable: string
        determiningFilters: string
        skipToFilters: string
        skipToResults: string
        resultsRelatedTo: string
      }
      HasFiltersResult: {
        title: string
      }
      SearchResultsTable: {
        expandRow: string
        collapseRow: string
        moreColumns: string
      }
      SearchResult: {
        details: string
      }
      FieldsForm: {
        from: string
        to: string
      }
      TableOfContents: {
        label: string
      }
      TimeDisplay: {
        relative: {
          secondsAgo: string
          minutesAgo: string
          hoursAgo: string
          daysAgo: string
          monthsAgo: string
          yearsAgo: string
          kiloYearsAgo: string
          megaYearsAgo: string
          gigaYearsAgo: string
          inSeconds: string
          inMinutes: string
          inHours: string
          inDays: string
          inMonths: string
          inYears: string
          inKiloYears: string
          inMegaYears: string
          inGigaYears: string
        }
      }
    }
    views: {
      DocumentGet: {
        tabs: {
          allProperties: string
          referencedBy: string
        }
      }
      DocumentEdit: {
        tabs: {
          allProperties: string
        }
        addClaim: string
        editClaim: string
        addSubClaim: string
        claimTypes: {
          identifier: string
          string: string
          html: string
          amount: string
          amountInterval: string
          time: string
          timeInterval: string
          link: string
          file: string
          reference: string
          has: string
          none: string
          unknown: string
        }
        labels: {
          link: string
          iri: string
          html: string
          string: string
          identifier: string
          amount: string
          file: string
          from: string
          to: string
        }
      }
    }
  }
}
